### ISSUE TITLE
Redirect Page Template is broken

### ISSUE THREAD

**Issue by friedrichweise** [Amani-Kinderdorf/amani_wordpress_theme#41]
Pages like this aren't working properly: https://www.amani-kinderdorf.de/freiwilligendienst/berichte-freiwilligendienst/

**Comment by Stunkymonkey** [comment]
solution for this would be to edit the `.htaccess` file in the wordpress folder

**Comment by friedrichweise** [comment]
Fixed in 9782fb111f60990d3f118eed12d1e2a81ae5487a

The current solution is a custom Page Template that redirects with `wp_redirect()` to the target category-page.
